version: '3.8'

services:
  mlflow:
    build:
      context: .
      dockerfile: docker/Dockerfile.mlflow
    container_name: mlflow_server
    command: 
      - mlflow
      - server
      - --host
      - 0.0.0.0
      - --port
      - "5000"
      - --backend-store-uri
      - sqlite:///mlflow.db
      - --serve-artifacts
      - --artifacts-destination
      - /app/mlartifacts
      - --allowed-hosts
      - "*"
    ports:
      - "5000:5000"
    volumes:
      - ./mlflow.db:/app/mlflow.db
      - ./mlartifacts:/app/mlartifacts
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    container_name: fast_api_server
    command: uvicorn src.api:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    volumes:
      - ./src:/app/src
      - ./models:/app/models
    depends_on:
      - mlflow
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
    container_name: streamlit_frontend
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://api:8000
    depends_on:
      - api
    restart: unless-stopped

  train:
    build:
      context: .
      dockerfile: docker/Dockerfile.train
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    volumes:
      - ./models:/app/models
      - ./mlflow.db:/app/mlflow.db
      - ./mlartifacts:/app/mlartifacts
      - ./data:/app/data
    depends_on:
      - mlflow
    profiles:
      - tools

  airflow:
    build:
      context: .
      dockerfile: docker/Dockerfile.airflow
    container_name: airflow_server
    command: standalone
    ports:
      - "8080:8080"
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - API_URL=http://api:8000
      - AIRFLOW_HOME=/opt/airflow
      - PYTHONPATH=/opt/airflow
      # Utilisateur admin par defaut
      - _AIRFLOW_WWW_USER_USERNAME=admin
      - _AIRFLOW_WWW_USER_PASSWORD=admin
      # Configuration locale pour la persistance
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=sqlite:////opt/airflow/airflow.db
    volumes:
      - ./dags:/opt/airflow/dags
      - ./src:/opt/airflow/src
      - ./data:/opt/airflow/data
      - ./models:/opt/airflow/models
      - ./mlartifacts:/opt/airflow/mlartifacts
      - ./mlflow.db:/opt/airflow/mlflow.db
      # On persiste la BDD interne d'Airflow
      - ./airflow.db:/opt/airflow/airflow.db
      - ./airflow_logs:/opt/airflow/logs
    depends_on:
      - mlflow
      - api
    restart: unless-stopped
