FROM apache/airflow:2.9.2-python3.11

USER airflow

# Installation des dependances du projet necessaires pour executer les DAGs
# On installe les packages ML et API utilises dans src/
RUN pip install --no-cache-dir \
    "xgboost>=2.0" \
    "lightgbm>=4.3" \
    "scikit-learn>=1.4" \
    "pandas>=2.0" \
    "mlflow>=2.12" \
    "optuna>=3.6" \
    "httpx>=0.27" \
    "joblib>=1.3"
